### ISSUE TITLE
npm上有两个包，该使用哪个呢？

### ISSUE THREAD

**Issue by kgloveyou** [CurryPaste/ws-heartbeat-ts#12]
https://www.npmjs.com/package/ws-heartbeat-ts，0.6.0 • Public • Published a year ago
https://www.npmjs.com/package/@findsoft/ws-heartbeat-ts，0.8.3 • Public • Published 3 months ago

**Comment by CurryPaste** [comment]
用 @findsoft 里的，那个是最新的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CurryPaste/ws-heartbeat-ts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月26日(星期四) 下午3:51
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[CurryPaste/ws-heartbeat-ts] npm上有两个包，该使用哪个呢？ (Issue #12)





 
https://www.npmjs.com/package/ws-heartbeat-ts，0.6.0 • Public • Published a year ago
 ***@***.***/ws-heartbeat-ts，0.8.3 • Public • Published 3 months ago

**Comment by CurryPaste** [comment]
用findsoft组织下的，个人包太久没更新了

> [https://www.npmjs.com/package/ws-heartbeat-ts，0.6.0](https://www.npmjs.com/package/ws-heartbeat-ts%EF%BC%8C0.6.0) • Public • Published a year ago [https://www.npmjs.com/package/@findsoft/ws-heartbeat-ts，0.8.3](https://www.npmjs.com/package/@findsoft/ws-heartbeat-ts%EF%BC%8C0.8.3) • Public • Published 3 months ago

**Comment by CurryPaste** [comment]
不过用的是一套代码，都是这个仓库
